### PR TITLE
Rewrite of the README, more open contribution rules

### PR DESCRIPTION
**Pull request by Crease29**
As discussed in our weekly meeting, I've rearranged the README.md and also made the contribution rules/instructions more open for new developers that are interested in contributing to Frosh.

### CODE REVIEW

**Comment by dneustadt** [comment]
I like it so far. IMHO all that is missing is the part concerning new plugin submissions in README.MD. Maybe it could read something like this:

> If you do want to contribute your own plugins, please be aware that we won't guarantee admission before you provide at least a functional prototype. The important thing is that **you** are convinced by your idea and you should be developing solely for this occasion.

**Comment by Crease29** [comment]
You're absolutely correct @dneustadt. I like your suggestion and have added it to the README.md.

**Review by dneustadt — CHANGES_REQUESTED** [review]
Emphasize the "you" to strengthen the point, meaning don't develop to become a member, develop based on your conviction.

> The important thing is that **you** are convinced [...]

**Comment by Crease29** [comment]
I missed that bold "you". This is fixed now.

**Review by dneustadt — APPROVED** [review]

**Review by shyim — APPROVED** [review]

**Pull request merged**
